name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-CI
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bleep
        uses: bleep-build/bleep-setup-action@0.0.1

      - name: Cache packages
        uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Run tests
        run: bleep --no-color test

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bleep
        uses: bleep-build/bleep-setup-action@0.0.1
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Cache packages
        uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Publish
        run: bleep publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.get_version.outputs.version-without-v }}"
          prerelease: false
          generate_release_notes: true
          files: |
